export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INPUT_TEXT = 'INPUT_TEXT';
export const COMMENT_CREATE = 'COMMENT_CREATE';
export const COMMENT_UPDATE = 'COMMENT_UPDATE';
export const COMMENT_DELETE = 'COMMENT_DELETE';

export const COMMENTS_LOAD = 'COMMENTS_LOAD';
export const LOADER_DISPALY_ON = 'COMMENTS_DISPALY_ON';
export const LOADER_DISPALY_OFF = 'COMMENTS_DISPALY_OFF';

export const ERROR_DISPALY_ON = 'ERROR_DISPALY_ON';
export const ERROR_DISPALY_OFF = 'ERROR_DISPALY_OFF';
